language: shell
os: linux

services:
  - docker
env:
  - OLS_VERSION=1.6.17 PHP_VERSION=lsphp74 FOLDER=template TAG=latest
  - OLS_VERSION=1.6.17 PHP_VERSION=lsphp74 FOLDER=template
  - OLS_VERSION=1.6.17 PHP_VERSION=lsphp73 FOLDER=template
